version: '3.1'

services:
    db:
        image: mysql:5.6
        ports:
            - 3306:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=thomas
    php:
        #image: php:5.6.31-apache
        build: ./environment/php-apache
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/thomas
            - ./cert:/etc/apache2/ssl
            - ./environment/php-apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./environment/php-apache/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./environment/php-apache/php.ini:/usr/local/etc/php/php.ini
            - ./environment/php-apache/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
