<?php
/**
 * @file
 * Code for the Vacations Excursions feature.
 */

include_once 'vacations_excursions.features.inc';

/**
 * Implements hook_node_validate()
 */
function vacations_excursions_node_validate($node, $form, &$form_state) {
  if ($node->type == 'excursion') {
    // Get the value of the field
    $wrapper = entity_metadata_wrapper('node', $node);
    $code = $wrapper->field_package_code->value();

    // Check that the value has 5 digits
    if (strlen($code) != 5)
    {
      form_set_error('field_package_code', t('Package code needs to be 5 digits'));
    }

    // Check that the value is unique
    // Execute a count query to see if there's other similar values.
    $query = new EntityFieldQuery;
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'excursion')
      ->fieldCondition('field_package_code','value', $code, '=')
      ->count();
    $count = $query->execute();

    if ($count > 0)
    {
      form_set_error('field_package_code', t('Package code %code already exists', array('%code' => $code)));
    }
  }
}
